"""customer projects phase 1

Revision ID: 8904db6a3fa5
Revises:
Create Date: 2026-08-27 18:02:27.822091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8904db6a3fa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('safe_diff_json', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_object_time', ['organization_id', 'object_type', 'object_id', 'occurred_at'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=True),
    sa.Column('customer_code', sa.String(length=40), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_owner_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('version > 0', name='ck_customer_version_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customer_org_normalized', ['organization_id', 'normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_membership_user')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_org_membership_active_user', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)

    op.create_table('project_status_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('stale_after_days', sa.Integer(), nullable=True),
    sa.Column('status_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('stale_after_days IS NULL OR stale_after_days > 0', name='ck_status_stale_days'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_project_status_org_code')
    )
    with op.batch_alter_table('project_status_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_catalog_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('assessment_grade', sa.String(length=4), nullable=True),
    sa.Column('probability_band', sa.Integer(), nullable=True),
    sa.Column('primary_sales_user_id', sa.Integer(), nullable=False),
    sa.Column('next_action', sa.String(length=500), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_meaningful_update_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_design_win_at', sa.Date(), nullable=True),
    sa.Column('expected_mass_production_at', sa.Date(), nullable=True),
    sa.Column('actual_mass_production_at', sa.Date(), nullable=True),
    sa.Column('close_reason_code', sa.String(length=64), nullable=True),
    sa.Column('close_notes', sa.Text(), nullable=True),
    sa.Column('paused_until', sa.Date(), nullable=True),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('derived_from_project_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('version > 0', name='ck_project_version_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['derived_from_project_id'], ['customer_projects.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['primary_sales_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_code', name='uq_project_org_code')
    )
    with op.batch_alter_table('customer_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_project_org_meaningful', ['organization_id', 'last_meaningful_update_at'], unique=False)
        batch_op.create_index('ix_project_org_normalized', ['organization_id', 'customer_id', 'normalized_name'], unique=False)
        batch_op.create_index('ix_project_org_sales_followup', ['organization_id', 'primary_sales_user_id', 'next_follow_up_at'], unique=False)
        batch_op.create_index('ix_project_org_stage', ['organization_id', 'stage_code'], unique=False)

    op.create_table('project_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_meaningful', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_activity_project_idempotency')
    )
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.create_index('ix_activity_project_time', ['project_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_activities_organization_id'), ['organization_id'], unique=False)

    op.create_table('project_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('promoted_brand', sa.String(length=120), nullable=False),
    sa.Column('promoted_mpn', sa.String(length=160), nullable=True),
    sa.Column('normalized_mpn', sa.String(length=160), nullable=True),
    sa.Column('mpn_pending', sa.Boolean(), nullable=False),
    sa.Column('customer_part_number', sa.String(length=160), nullable=True),
    sa.Column('application_position', sa.String(length=255), nullable=True),
    sa.Column('estimated_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity_period', sa.String(length=20), nullable=True),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('technical_status', sa.String(length=64), nullable=True),
    sa.Column('commercial_status', sa.String(length=64), nullable=True),
    sa.Column('expected_mass_production_at', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('version > 0', name='ck_material_version_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_material_project_idempotency')
    )
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.create_index('ix_material_org_brand_mpn', ['organization_id', 'promoted_brand', 'normalized_mpn'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_materials_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_materials_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notification_preferences_json', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'role_code', name='uq_project_member_role')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)

    op.create_table('project_stage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('from_stage_code', sa.String(length=32), nullable=True),
    sa.Column('to_stage_code', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['customer_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_stage_event_project_idempotency')
    )
    with op.batch_alter_table('project_stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stage_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_stage_event_project_time', ['project_id', 'occurred_at'], unique=False)

    op.create_table('material_competitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_material_id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('mpn', sa.String(length=160), nullable=True),
    sa.Column('normalized_mpn', sa.String(length=160), nullable=True),
    sa.Column('distributor', sa.String(length=160), nullable=True),
    sa.Column('model_pending', sa.Boolean(), nullable=False),
    sa.Column('incumbent_status', sa.String(length=64), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=32), nullable=True),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('version > 0', name='ck_competitor_version_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_material_id'], ['project_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_material_id', 'idempotency_key', name='uq_competitor_material_idempotency')
    )
    with op.batch_alter_table('material_competitors', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_org_brand_mpn', ['organization_id', 'brand', 'normalized_mpn'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_competitors_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_competitors_project_material_id'), ['project_material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_competitors_project_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_competitors_organization_id'))
        batch_op.drop_index('ix_competitor_org_brand_mpn')

    op.drop_table('material_competitors')
    with op.batch_alter_table('project_stage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_stage_event_project_time')
        batch_op.drop_index(batch_op.f('ix_project_stage_events_organization_id'))

    op.drop_table('project_stage_events')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_organization_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_materials_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_materials_organization_id'))
        batch_op.drop_index('ix_material_org_brand_mpn')

    op.drop_table('project_materials')
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_activities_organization_id'))
        batch_op.drop_index('ix_activity_project_time')

    op.drop_table('project_activities')
    with op.batch_alter_table('customer_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_project_org_stage')
        batch_op.drop_index('ix_project_org_sales_followup')
        batch_op.drop_index('ix_project_org_normalized')
        batch_op.drop_index('ix_project_org_meaningful')
        batch_op.drop_index(batch_op.f('ix_customer_projects_organization_id'))

    op.drop_table('customer_projects')
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contacts_organization_id'))

    op.drop_table('customer_contacts')
    with op.batch_alter_table('project_status_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status_catalog_organization_id'))

    op.drop_table('project_status_catalog')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))
        batch_op.drop_index('ix_org_membership_active_user')

    op.drop_table('organization_memberships')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_organization_id'))
        batch_op.drop_index('ix_customer_org_normalized')

    op.drop_table('customers')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_object_time')
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_status'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
